site_name: Zack's Linux Hacker Notes
site_description: Personal notes and resources for learning Linux
site_author: Zackry Langford

# Repository
repo_name: linux-hacker-notes
repo_url: https://github.com/zackrylangford/linux-hacker-notes

# Theme configuration
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - search.share
    - content.code.copy

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - tables
  - footnotes

# Navigation structure
nav:
  - Home: index.md
  - Commands: 
      - Overview: commands/index.md
  - Projects: projects/index.md
  - Lessons: lessons/index.md
  - Scripts: scripts/index.md
  - Distributions:
      - Overview: distributions/index.md
  - Journal: journal/index.md
  - Thoughts: thoughts/index.md

# Plugins
plugins:
  - search