site_name: Linux Hacker Notes
site_description: A focused guide to becoming an expert Linux hacker
site_author: Zack

# Repository
repo_name: zackrylangford/linux-hacker-notes
repo_url: https://github.com/zackrylangford/linux-hacker-notes

# Theme configuration
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - tables
  - footnotes
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Navigation structure
nav:
  - Home: index.md
  - Fundamentals:
      - Overview: fundamentals/index.md
      - Command Line Basics: fundamentals/command-line-basics.md
      - File System Structure: fundamentals/file-system.md
      - User Management: fundamentals/user-management.md
      - Package Management: fundamentals/package-management.md
  - System Administration:
      - Overview: sysadmin/index.md
      - System Monitoring: sysadmin/monitoring.md
      - Service Management: sysadmin/services.md
      - Networking: sysadmin/networking.md
      - Security: sysadmin/security.md
  - Distributions:
      - Overview: distributions/index.md
      - Arch-based: distributions/arch-based/index.md
      - Debian-based: distributions/debian-based/index.md
  - Hacking Lab:
      - Overview: hacking-lab/index.md
      - Projects: hacking-lab/projects.md
      - Challenges: hacking-lab/challenges.md
  - Reference:
      - Overview: reference/index.md
      - Command Cheatsheet: reference/commands/index.md
      - Configuration Files: reference/config-files/index.md
      - Troubleshooting: reference/troubleshooting.md

# Plugins
plugins:
  - search