site_name: Zack's Linux Hacker Notes
site_description: Personal notes and resources for learning Linux distributions
site_author: Zack

# Repository
repo_name: zackrylangford/linux-hacker-notes
repo_url: https://github.com/zackrylangford/linux-hacker-notes

# Theme configuration
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - content.code.copy

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - tables
  - footnotes

# Navigation structure
nav:
  - Home: index.md
  - Distributions: distributions/index.md
  - Journal: journal/index.md
  - Projects: projects/index.md

# Plugins
plugins:
  - search